### ISSUE TITLE
[SECURITY] Major Security Vulnerabilities in many packages.

### ISSUE THREAD

**Issue by BlockArchitech** [znci/i#3]
Many packages have Security Vulnerabilities. Please see dependabot alerts.

**Comment by BlockArchitech** [comment]
Assigning @zNotChill because I do not want to go through 1400 lines of package-lock.json. Have fun.

**Comment by zNotChill** [comment]
bloody hell what has happened to these packages then

**Comment by BlockArchitech** [comment]
codeql is exist now

**Comment by BlockArchitech** [comment]
https://github.com/znci/i/actions/runs/2180025142

**Comment by zNotChill** [comment]
ok let me see

**Comment by BlockArchitech** [comment]
Fixed

**Comment by zNotChill** [comment]
alright cool, is there any more packages with vulnerabilities? and how did all these security issues even begin? was it moment or node-fetch or something?

**Comment by zNotChill** [comment]
also im @ school so I won't reply until I'm home

**Comment by BlockArchitech** [comment]
> alright cool, is there any more packages with vulnerabilities? and how did all these security issues even begin? was it moment or node-fetch or something?

Yes.

Directory was deleted. #4 #2 #1

**Comment by zNotChill** [comment]
dont care anymore doesnt seem to be an issue anymore
